//! Deterministic Trajectory Ledger fixture for the F8 replay viewer.
//!
//! Per F8-B / ADR-010 / issue #63. Writes a ledger covering every
//! entry type the viewer renders, with **real** chain hashes computed
//! by the canonical LedgerWriter. The viewer's in-browser SHA-256
//! walk against this file must produce a verified banner; the
//! committed copy at `tools/replay-viewer/fixtures/sample-session.jsonl`
//! is regenerated by running this example.
//!
//! Usage:
//!
//! ```bash
//! cargo run -p aegis-ledger-writer --example replay-fixture -- \
//!   tools/replay-viewer/fixtures/sample-session.jsonl
//! ```
//!
//! The output is byte-deterministic — committing the rendered file
//! gives us a stable test artifact for both the Rust verifier
//! (`verify_file`) and the JS verifier in the browser. UUIDs and
//! timestamps are pinned; SHA-256 is content-addressed.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::PathBuf;

use aegis_ledger_writer::{verify_file, Entry, EntryType, LedgerWriter};
use chrono::{TimeZone, Utc};
use serde_json::{json, Map, Value};
use uuid::Uuid;

fn main() {
    let out: PathBuf = std::env::args()
        .nth(1)
        .expect("usage: replay-fixture <out-path>")
        .into();

    if out.exists() {
        std::fs::remove_file(&out).expect("remove old fixture");
    }

    let session_id = "session-replay-fixture".to_string();

    // Pinned UUIDv7s — incrementing the counter byte by byte so each
    // entry's UUID is human-readable and the output stays stable.
    let mut counter: u8 = 1;
    let next_uuid = move || -> Uuid {
        let mut bytes = [0u8; 16];
        // UUID v7 layout: 48-bit timestamp || version=7 || ... .
        // We don't care about UUID semantics here, just determinism;
        // every byte set to `counter` produces a valid 16-byte ID
        // accepted by parsers.
        bytes.fill(counter);
        // version nibble (bits 12-15 of clock_seq_hi) — set to 7.
        bytes[6] = 0x70 | (bytes[6] & 0x0F);
        // variant bits (bits 0-1 of clock_seq_hi) — set to 10.
        bytes[8] = 0x80 | (bytes[8] & 0x3F);
        counter = counter.wrapping_add(1);
        Uuid::from_bytes(bytes)
    };

    let mut w =
        LedgerWriter::create_with_uuid_generator(&out, session_id.clone(), Box::new(next_uuid))
            .expect("open writer");

    // Pinned agent identity hash for stability.
    let agent_hash = [0x3Bu8; 32];
    let model_digest = [0xA3u8; 32];
    let manifest_digest = [0xB4u8; 32];
    let config_digest = [0xC5u8; 32];

    let ts = |s: u32| Utc.with_ymd_and_hms(2026, 4, 29, 14, 0, s).unwrap();

    // 0. session_start
    let mut p = Map::new();
    p.insert(
        "spiffeId".to_string(),
        Value::String("spiffe://aegis-node.local/agent/research-mcp/inst-001".to_string()),
    );
    p.insert(
        "modelDigestHex".to_string(),
        Value::String(hex::encode(model_digest)),
    );
    p.insert(
        "manifestDigestHex".to_string(),
        Value::String(hex::encode(manifest_digest)),
    );
    p.insert(
        "configDigestHex".to_string(),
        Value::String(hex::encode(config_digest)),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::SessionStart,
        agent_identity_hash: agent_hash,
        timestamp: ts(0),
        payload: p,
    })
    .unwrap();

    // 1. reasoning_step (F5) for the read.
    let rstep1 = "rstep-q1-readsales";
    let mut p = Map::new();
    p.insert(
        "reasoningStepId".to_string(),
        Value::String(rstep1.to_string()),
    );
    p.insert(
        "input".to_string(),
        Value::String("Summarize Q1 sales reports under /data/reports.".to_string()),
    );
    p.insert(
        "reasoning".to_string(),
        Value::String(
            "I need the contents of the Q1 reports. The MCP filesystem server's read_text_file is the right call."
                .to_string(),
        ),
    );
    p.insert(
        "toolsConsidered".to_string(),
        json!(["read_text_file", "list_directory", "write_file"]),
    );
    p.insert(
        "toolSelected".to_string(),
        Value::String("read_text_file".to_string()),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::ReasoningStep,
        agent_identity_hash: agent_hash,
        timestamp: ts(1),
        payload: p,
    })
    .unwrap();

    // 2. access — the MCP tool call summary entry.
    let mut p = Map::new();
    p.insert(
        "resourceUri".to_string(),
        Value::String("mcp://filesystem/read_text_file".to_string()),
    );
    p.insert(
        "accessType".to_string(),
        Value::String("mcp_tool_call".to_string()),
    );
    p.insert("bytesAccessed".to_string(), json!(482));
    p.insert(
        "reasoningStepId".to_string(),
        Value::String(rstep1.to_string()),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::Access,
        agent_identity_hash: agent_hash,
        timestamp: ts(2),
        payload: p,
    })
    .unwrap();

    // 3. access — the underlying fs read.
    let mut p = Map::new();
    p.insert(
        "resourceUri".to_string(),
        Value::String("file:///data/reports/q1.md".to_string()),
    );
    p.insert("accessType".to_string(), Value::String("read".to_string()));
    p.insert("bytesAccessed".to_string(), json!(482));
    p.insert(
        "reasoningStepId".to_string(),
        Value::String(rstep1.to_string()),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::Access,
        agent_identity_hash: agent_hash,
        timestamp: ts(3),
        payload: p,
    })
    .unwrap();

    // 4. reasoning_step for the write.
    let rstep2 = "rstep-writesum";
    let mut p = Map::new();
    p.insert(
        "reasoningStepId".to_string(),
        Value::String(rstep2.to_string()),
    );
    p.insert(
        "input".to_string(),
        Value::String("User asked: Summarize Q1 sales reports.".to_string()),
    );
    p.insert(
        "reasoning".to_string(),
        Value::String(
            "I'll draft a summary and write it to /data/output/summary.md so the user can pick it up."
                .to_string(),
        ),
    );
    p.insert("toolsConsidered".to_string(), json!(["write_file"]));
    p.insert(
        "toolSelected".to_string(),
        Value::String("write_file".to_string()),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::ReasoningStep,
        agent_identity_hash: agent_hash,
        timestamp: ts(4),
        payload: p,
    })
    .unwrap();

    // 5. violation — write_file isn't in tools.mcp[].allowed_tools.
    let mut p = Map::new();
    p.insert(
        "resourceUri".to_string(),
        Value::String("mcp://filesystem/write_file".to_string()),
    );
    p.insert(
        "accessType".to_string(),
        Value::String("mcp_tool_call".to_string()),
    );
    p.insert(
        "violationReason".to_string(),
        Value::String(
            "mcp tool call \"filesystem\"/\"write_file\" not granted: tool not in allowed_tools"
                .to_string(),
        ),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::Violation,
        agent_identity_hash: agent_hash,
        timestamp: ts(5),
        payload: p,
    })
    .unwrap();

    // 6. approval_request — agent falls back to a write that needs approval.
    let mut p = Map::new();
    p.insert(
        "actionSummary".to_string(),
        Value::String("Write summary to /data/output/summary.md".to_string()),
    );
    p.insert(
        "resourceUri".to_string(),
        Value::String("file:///data/output/summary.md".to_string()),
    );
    p.insert("accessType".to_string(), Value::String("write".to_string()));
    p.insert(
        "expiresAt".to_string(),
        Value::String("2026-04-29T14:02:06Z".to_string()),
    );
    p.insert(
        "reasoningStepId".to_string(),
        Value::String(rstep2.to_string()),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::ApprovalRequest,
        agent_identity_hash: agent_hash,
        timestamp: ts(6),
        payload: p,
    })
    .unwrap();

    // 7. approval_granted.
    let mut p = Map::new();
    p.insert("decision".to_string(), Value::String("granted".to_string()));
    p.insert(
        "approverId".to_string(),
        Value::String("spiffe://aegis-node.local/operator/security".to_string()),
    );
    p.insert(
        "decidedAt".to_string(),
        Value::String("2026-04-29T14:00:06Z".to_string()),
    );
    p.insert(
        "reasoningStepId".to_string(),
        Value::String(rstep2.to_string()),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::ApprovalGranted,
        agent_identity_hash: agent_hash,
        timestamp: ts(7),
        payload: p,
    })
    .unwrap();

    // 8. access — the actual write.
    let mut p = Map::new();
    p.insert(
        "resourceUri".to_string(),
        Value::String("file:///data/output/summary.md".to_string()),
    );
    p.insert("accessType".to_string(), Value::String("write".to_string()));
    p.insert("bytesAccessed".to_string(), json!(214));
    p.insert(
        "reasoningStepId".to_string(),
        Value::String(rstep2.to_string()),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::Access,
        agent_identity_hash: agent_hash,
        timestamp: ts(8),
        payload: p,
    })
    .unwrap();

    // 9. network_attestation (F6) — zero-connection session.
    let mut p = Map::new();
    p.insert("totalConnections".to_string(), json!(0));
    p.insert("allowedCount".to_string(), json!(0));
    p.insert("approvedCount".to_string(), json!(0));
    p.insert("deniedCount".to_string(), json!(0));
    p.insert(
        "connectionsDigestHex".to_string(),
        Value::String(
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855".to_string(),
        ),
    );
    p.insert("networkConnectionsObserved".to_string(), json!([]));
    p.insert(
        "signatureHex".to_string(),
        Value::String(
            "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff".to_string(),
        ),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::NetworkAttestation,
        agent_identity_hash: agent_hash,
        timestamp: ts(9),
        payload: p,
    })
    .unwrap();

    // 10. session_end.
    let mut p = Map::new();
    p.insert(
        "spiffeId".to_string(),
        Value::String("spiffe://aegis-node.local/agent/research-mcp/inst-001".to_string()),
    );
    w.append(Entry {
        session_id: session_id.clone(),
        entry_type: EntryType::SessionEnd,
        agent_identity_hash: agent_hash,
        timestamp: ts(10),
        payload: p,
    })
    .unwrap();

    let root = w.close().unwrap();
    println!("wrote {}", out.display());
    println!("root hash: {}", hex::encode(root));

    // Round-trip verify so a broken generator never produces a bad
    // committed fixture.
    let summary = verify_file(&out).expect("re-verify generated fixture");
    println!(
        "verified: {} entries, root {}",
        summary.entry_count, summary.root_hash_hex
    );
    assert_eq!(summary.root_hash_hex, hex::encode(root));
}
