//! FFI bindings to LiteRT-LM's C engine ABI.
//!
//! The bindings are generated by `build.rs` from the vendored
//! `c/engine.h` against the `.so` published by
//! `.github/workflows/litertlm-runtime-publish.yml` — both pinned by
//! SHA-256 in the build script. See
//! [ADR-023](../../docs/adrs/023-litertlm-as-second-inference-backend.md)
//! for the architectural rationale and
//! [ADR-014](../../docs/adrs/014-cpu-first-gguf-inference-via-llama-cpp.md)
//! for the FFI safety posture mirrored from `aegis-llama-backend`.
//!
//! # Safety
//!
//! Every binding here is `unsafe` — direct FFI into a C ABI. Callers
//! must hold the invariants documented in `c/engine.h` (opaque pointer
//! lifetime, single-threaded session use, etc.). The safe wrapper
//! lives in [`aegis-litertlm-backend`](../aegis_litertlm_backend),
//! which encapsulates each `unsafe` call with a documented invariant.
//!
//! # Stability
//!
//! The upstream LiteRT-LM tag is pinned in `build.rs`. CI rebuilds
//! against that pin and refuses upstream drift without an explicit
//! version bump (per the LiteRT-A acceptance criteria, mirroring
//! ADR-014's "pinned upstream" rule).

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]
#![allow(unsafe_op_in_unsafe_fn)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
