import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Diataxis-aligned sidebar. The actual markdown lives in the repo-root
// `../docs/` tree; doc IDs below match relative paths (without the .md
// extension) under that root.
//
// The structure is intentionally hand-curated rather than autogenerated:
// the docs/ tree mixes ADRs, plans, research notes, and operator guides,
// and Diataxis only makes sense if we choose where each lands.
//
// Sections that don't have a written page yet (e.g. a synthesised
// "Quick start" tutorial) are deliberately omitted — add them as the
// content is authored, don't fake them with placeholders.
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'How-to guides',
      description: 'Task-oriented guides for operators and contributors.',
      collapsed: false,
      items: [
        'INSTALL',
        'CHAT',
        'MODEL_MIRRORING',
        'SUPPLY_CHAIN',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      description: 'What the project guarantees, and how to read its outputs.',
      collapsed: false,
      items: [
        'COMPATIBILITY_CHARTER',
        'COMPLIANCE_MATRIX',
      ],
    },
    {
      type: 'category',
      label: 'Explanation — Architecture decisions',
      description: 'ADRs capturing the why behind each design choice.',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'adrs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Explanation — Plans & research',
      description: 'Phase plans and security research briefs.',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'plans',
        },
        {
          type: 'autogenerated',
          dirName: 'research',
        },
      ],
    },
  ],
};

export default sidebars;
